### ISSUE TITLE
Failed to handle packet when stepping in puddle

### ISSUE THREAD

**Issue by IAmSneak** [HexBugOrion/UnEarthed#40]
Someone stepped in a puddle and were kicked from the server. This was in the server console:

[00:30:51] [Server thread/WARN]: Failed to handle packet for /[IP]
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bpn000$modifiedRunLoop(MinecraftServer.java:8810) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{unearthed:puddle}
        at net.minecraft.class_2688.method_11654(class_2688.java:95) ~[intermediary-server.jar:?]
        at net.minecraft.class_1894.method_8236(class_1894.java:57) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6126(class_1309.java:493) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_6126(class_3222.java:917) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5670(class_1309.java:376) ~[intermediary-server.jar:?]
        at net.minecraft.class_1297.method_5773(class_1297.java:431) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2209) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
        ... 10 more

**Comment by lilypuree** [comment]
Please provide more info, as well as the full crash log.

**Comment by IAmSneak** [comment]
Minecraft 1.16.4
Unearthed V1.1

Player stepped into puddle and was kicked from the server. Every time they tried to rejoin the server they were kicked. They puddle was removed and they were able to rejoin. The server didn't crash, neither did the client, so no crash report can be provided.
