### ISSUE TITLE
UnEarthed Crashes Server on Startup

### ISSUE THREAD

**Issue by Cluelesshobo** [HexBugOrion/UnEarthed#5]
What mods are side-loaded does not affect unearthed's result.

`Exception in thread "main" [13:11:52] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
[13:11:52] [main/INFO]: [STDERR]:       ... 1 more
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
[13:11:52] [main/INFO]: [STDERR]:       ... 2 more
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:229)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
[13:11:52] [main/INFO]: [STDERR]:       ... 7 more
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[13:11:52] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
[13:11:52] [main/INFO]: [STDERR]:       ... 9 more
[13:11:52] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2378.method_10250(net.minecraft.class_2960)'
[13:11:52] [main/INFO]: [STDERR]:       at net.oriondevcorgitaco.unearthed.util.RegistrationHelper.registerFeature(RegistrationHelper.java:20)
[13:11:52] [main/INFO]: [STDERR]:       at net.oriondevcorgitaco.unearthed.world.feature.naturalgenerators.NaturalGenerator.<clinit>(NaturalGenerator.java:25)
[13:11:52] [main/INFO]: [STDERR]:       at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:175)
[13:11:52] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:116)
[13:11:52] [main/INFO]: [STDERR]:       ... 14 more`

**Comment by CorgiTaco** [comment]
Could you send your modlist and a copy paste of your crash with https://hatebin.com/

**Comment by Cluelesshobo** [comment]
The mods are Fabric API, Lithium, and Phosphor, even with only fabric API the crash happens.
https://hatebin.com/asbagnvhsy Full log.

**Comment by Cluelesshobo** [comment]
Crashing still persists on v1.0.3 on stock Fabric Server with Fabric API.

**Comment by rafaelkai** [comment]
This happens on the forge version aswell

**Comment by CorgiTaco** [comment]
@rafaelkai send your crashlog and latest.log

**Comment by rafaelkai** [comment]
latest.log:  https://hatebin.com/mohvlrftwm

The issue doesn't seem to generate a crashlog

**Comment by RDKRACZ** [comment]
Same for me - only unearthed and fabric api

https://hatebin.com/mzrjqmulmt

**Comment by CorgiTaco** [comment]
Patched: [Forge 1.16.2/3] https://www.curseforge.com/minecraft/mc-mods/unearthed-forge/files/3089010
[Fabric 1.16.2/3] https://www.curseforge.com/minecraft/mc-mods/unearthed-fabric/files/3089015
