### ISSUE TITLE
[1.16.5 Forge Crash] "Critical injection failure"

### ISSUE THREAD

**Issue by CactusDuud** [HexBugOrion/UnEarthed#64]
```
[12:11:02] [pool-3-thread-1/ERROR]: Critical injection failure: LVT in net/minecraft/world/gen/FlatGenerationSettings::func_236942_c_()Lnet/minecraft/world/biome/Biome; has incompatible changes at opcode 286 in callback net/minecraft/world/gen/FlatGenerationSettings::addUnearthedFeature.
Expected: [Lnet/minecraft/world/biome/Biome;, Lnet/minecraft/world/biome/BiomeGenerationSettings;, Lnet/minecraft/world/biome/BiomeGenerationSettings$Builder;, Z, [Lnet/minecraft/block/BlockState;]
   Found: [Lnet/minecraft/world/biome/Biome;, Lnet/minecraft/world/biome/BiomeGenerationSettings;, Lnet/minecraft/world/biome/BiomeGenerationSettings$Builder;, Ljava/util/Map;, Z]
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/567160397.call(Unknown Source)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[12:11:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.FlatChunkGenerator.<clinit>(SourceFile:21)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.ChunkGenerator.<clinit>(SourceFile:54)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.func_243579_h(Registry.java:294)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry$$Lambda$713/1465912700.get(Unknown Source)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.lambda$static$51(Registry.java:466)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry$$Lambda$2268/1492045573.accept(Unknown Source)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$666/1592044243.run(Unknown Source)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:11:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/world/gen/FlatGenerationSettings::func_236942_c_()Lnet/minecraft/world/biome/Biome; has incompatible changes at opcode 286 in callback net/minecraft/world/gen/FlatGenerationSettings::addUnearthedFeature.
Expected: [Lnet/minecraft/world/biome/Biome;, Lnet/minecraft/world/biome/BiomeGenerationSettings;, Lnet/minecraft/world/biome/BiomeGenerationSettings$Builder;, Z, [Lnet/minecraft/block/BlockState;]
   Found: [Lnet/minecraft/world/biome/Biome;, Lnet/minecraft/world/biome/BiomeGenerationSettings;, Lnet/minecraft/world/biome/BiomeGenerationSettings$Builder;, Ljava/util/Map;, Z]
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[12:11:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 26 more
```

Let me know if you need more info. I have a pretty large modpack but I have narrowed the crash down to Unearthed.

**Comment by MickeyMouseYT** [comment]
Yeah i have the same problem.

**Comment by Raithion** [comment]
Having the same issue, hoping it gets fixed soon.

**Comment by Demodus** [comment]
Seems to happen to me only with Forge 36.1.18 and newer.   Forge will load with UnEarth disabled.

**Comment by TheWitherlord** [comment]
Same exact issue here

**Comment by MickeyMouseYT** [comment]
@CorgiTaco

**Comment by CorgiTaco** [comment]
Pinging is not gonna fix the issue faster first off

**Comment by MickeyMouseYT** [comment]
> Le ping ne résoudra pas le problème plus rapidement en premier

???
